version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      # These variables are used by the backend to connect to the database
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ailoganalyzer
      PYTHON_SERVICE_URL: http://python-service:5000
      # The .env file in the 'backend' folder provides the following keys:
      # - API_KEY
      # - SENDGRID_API_KEY
      # - EMAIL_FROM_ADDRESS
      # - TWILIO_ACCOUNT_SID
      # - TWILIO_AUTH_TOKEN
      # - TWILIO_PHONE_NUMBER
    env_file:
      - ./backend/.env

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000


  db:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ailoganalyzer
    ports:
      # You can optionally expose the port to connect with a DB tool like DBeaver
      - "5435:5432" 
    volumes:
      # This will persist the database data on your local machine
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
